#define INTIMATE_SLOT_GENITAL 1
#define INTIMATE_SLOT_REAR 2
#define INTIMATE_SLOT_BREAST 3
#define INTIMATE_SLOT_MOUTH 4
#define INTIMATE_SLOT_MISC INTIMATE_SLOT_MOUTH

#define INTIMATE_FLAG_INSERTABLE (1<<0) 
#define INTIMATE_FLAG_PIERCING (1<<1) 
#define INTIMATE_FLAG_LOCKABLE (1<<2)
#define INTIMATE_FLAG_REMOTE (1<<3) 
#define INTIMATE_FLAG_BERIDDLEABLE (1<<4)

#define TRAIT_SOURCE_INTIMATE "intimate_accessory"
